apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
        - name: udagram-api-user
          image: saberguirat/udagram-api-user:v2
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
      restartPolicy: Always
